um = float(input('Digite seu número: '))
print('-' * 12)
print('{} * {:2} = {}'.format(um, 0, um*0))
print('{} * {:2} = {}'.format(um, 1, um*1))
print('{} * {:2} = {}'.format(um, 2, um*2))
print('{} * {:2} = {}'.format(um, 3, um*3))
print('{} * {:2} = {}'.format(um, 4, um*4))
print('{} * {:2} = {}'.format(um, 5, um*5))
print('{} * {:2} = {}'.format(um, 6, um*6))
print('{} * {:2} = {}'.format(um, 7, um*7))
print('{} * {:2} = {}'.format(um, 8, um*8))
print('{} * {:2} = {}'.format(um, 9, um*9))
print('{} * {:2} = {}'.format(um, 10, um*10))
print('-' * 12)
